project:
  type: book

book:
  title: "Mastering ggplot2: From Novice to Data Viz Pro"
  subtitle: "Unleash Your Inner Data Scientist"
  author: "Tuhin Rana"
  date: "3/17/2023"
  repo-url: https://github.com/rana2hin/ggplot_guide/
  sharing: [facebook, twitter]
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - intro.qmd
    - ch2.qmd
    - ch3.qmd
    - ch4.qmd
    - ch5.qmd
    - ch6.qmd
    - ch7.qmd
    - ch8.qmd
    - ch9.qmd
    - ch10.qmd
    - ch11.qmd
    - ch12.qmd
    - ch13.qmd
    - ch14.qmd
    - ch15.qmd
    - ch16.qmd
    - ch17.qmd
    - ch18.qmd
    - ch19.qmd
    - ch20.qmd
    - summary.qmd

format:
  html:
    theme: journal
  pdf: 
    documentclass: scrbook
    keep-tex: true
    papersize: letter
    toc: true
    toc-depth: 2
    toc-title: Table of Contents
    geometry:
      - top=30mm
      - left=20mm
      - heightrounded
    fontfamily: libertinus
    colorlinks: true
  epub:
    fig-format: png
  docx:
    toc: true
    toc-depth: 2
    toc-title: Table of Contents
    number-sections: true