project:
  type: book

book:
  title: "ggplot2: Unleash Your Inner Artist"
  author: "Tuhin rana"
  date: "3/17/2024"
  repo-url: https://github.com/rana2hin/ggplot_guide/
  sharing: [facebook, twitter]
  chapters:
    - index.qmd
    - intro.qmd
    - ch2.qmd
    - ch3.qmd
    - ch4.qmd
    - ch5.qmd
    - ch6.qmd
    - ch7.qmd
    - ch8.qmd
    - ch9.qmd
    - ch10.qmd
    - ch11.qmd
    - ch12.qmd
    - ch13.qmd
    - ch14.qmd
    - ch15.qmd
    - ch16.qmd
    - ch17.qmd
    - ch18.qmd
    - ch19.qmd
    - ch20.qmd
    - summary.qmd

format:
  html:
    theme: cosmo
